language: python

python:
  - "2.7"
  # - "3.4"

env:
  # - CORE_BRANCH=stable6
  - CORE_BRANCH=stable7

before_install:
- sudo add-apt-repository -y ppa:ondrej/php5
- sudo apt-get update
- sudo apt-get install apache2 apache2.2-common php5 php5-cli php5-sqlite php5-fpm php5-gd php5-json php5-mcrypt sqlite3 libapache2-mod-fastcgi
# enable php-fpm
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" | sudo tee --append /etc/php5/fpm/php.ini
- sudo service php5-fpm start
# configure apache virtual hosts
- sudo cp -f travis-build/travis-ci-apache /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
- sudo service apache2 restart
# install OC
- bash travis-build/install_oc.sh $CORE_BRANCH
- sudo chown -R www-data:www-data core/{config,data}
- sudo chmod -R g+w core/{config,data}
- dpkg-query -L php5-sqlite
- dpkg-query -L sqlite3
- cat /etc/php5/conf.d/pdo_sqlite.ini
- cat /etc/php5/conf.d/sqlite3.ini
- ls -la /etc/php5/fpm
- ls -la /etc/php5/fpm/conf.d
- grep -i sqlite /etc/php5/fpm/php.ini

install:
  - pip install requests unittest-data-provider

script:
  # execute unit tests
  - ./runtests.sh

after_failure:
  - sudo cat core/data/owncloud.log

